function LoadCliqueUkrainizer()
  if IsAddOnLoaded("Clique") then
    local L = Clique.L
    local current_locale = GetLocale()
    if not L then return end

    local baseLocale = {
      ["A binding that belongs to the 'default' binding-set will always be active on your unit frames, unless you override it with another binding."] = "Прив'язка, яка належить до набору прив'язок 'default', завжди буде активна на ваших рамках юнітів, якщо ви не перезапишете її іншою прив'язкою.",
      ["A binding that belongs to the 'enemy' binding-set will always be active when clicking on unit frames that display enemy units, i.e. those you can attack. If you click on a unit that you cannot attack, nothing will happen."] = "Прив'язка, яка належить до набору прив'язок 'enemy', завжди буде активна при натисканні на рамки юнітів, які відображають ворожі одиниці, тобто тих, на яких ви можете атакувати. Якщо ви натиснете на юніта, якого ви не можете атакувати, нічого не станеться.",
      ["A binding that belongs to the 'frield' binding-set will only be active when clicking on unit frames that display friendly units, i.e. those you can heal and assist. If you click on a unit that you cannot heal or assist, nothing will happen."] = "Прив'язка, яка належить до набору прив'язок 'frield', буде активна лише при натисканні на рамки юнітів, які відображають дружні одиниці, тобто тих, яких ви можете лікувати або допомагати. Якщо ви натиснете на юніта, кого ви не можете лікувати або допомагати, нічого не станеться.",
      ["A binding that belongs to the 'global' binding-set is always active. If the spell requires a target, you will be given the 'casting hand', otherwise the spell will be cast. If the spell is an AOE spell, then you will be given the ground targeting circle."] = "Прив'язка, яка належить до набору прив'язок 'global', завжди активна. Якщо заклинання потребує ціль, вам буде надано 'руку заклинання', інакше заклинання буде залито. Якщо заклинання є зоновим, вам буде надано коло для вибору місця на землі.",
      ["A binding that belongs to the 'hovercast' binding-set is active whenever the mouse is over a unit frame, or a character in the 3D world. This allows you to use 'hovercasting', where you hover over a unit in the world and press a key to cast a spell on them. THese bindings are also active over unit frames."] = "Прив'язка, яка належить до набору прив'язок 'hovercast', активна, коли миша перебуває над рамкою юніта або персонажем у 3D-світі. Це дозволяє вам використовувати 'hovercasting', де ви наводите курсор на юніта в світі і натискаєте клавішу, щоб на нього наложити заклинання. Ці прив'язки також активні на рамках юнітів.",
      ["A binding that belongs to the 'ooc' binding-set will only be active when the player is out-of-combat, regardless of the other binding-sets this binding belongs to. As soon as the player enters combat, these bindings will no longer be active, so be careful when choosing this binding-set for any spells you use frequently."] = "Прив'язка, яка належить до набору прив'язок 'ooc', буде активна лише тоді, коли гравець не в бою, незалежно від інших наборів прив'язок, до яких належить ця прив'язка. Як тільки гравець потрапляє в бій, ці прив'язки стають неактивними, тому будьте обережні, обираючи цей набір прив'язок для часто використовуваних заклинань.",
      ["A binding that belongs to this binding-set is only active when the player has the given talent specialization active"] = "Прив'язка, яка належить до цього набору прив'язок, активна лише тоді, коли гравець має активний відповідний талантовий набір",
      ["Accept"] = "Прийняти",
      ["Action"] = "Дія",
      ["Add new profile"] = "Додати новий профіль",
      ["Alt"] = "Alt",
      ["Arena enemy frames"] = "Рамки ворожих арен",
      ["Attempt to fix the issue introduced in 4.3 with casting on dead targets"] = "Спроба виправити проблему, введену в 4.3, з заклинанням на мертвих цілях",
      ["Bind other"] = "Прив'язати інше",
      ["Bind spell"] = "Прив'язати заклинання",
      ["Binding"] = "Прив'язка",
      ["Blizzard frame integration options"] = "Параметри інтеграції рамок Blizzard",
      ["Boss target frames"] = "Рамки цілей босів",
      ["Cancel"] = "Скасувати",
      ["Cast %s"] = "Накладання %s",
      ["Change binding"] = "Змінити прив'язку",
      ["Change binding: %s"] = "Змінити прив'язку: %s",
      ["Clique Binding Configuration"] = "Конфігурація прив'язок Clique",
      ["Clique binding configuration"] = "Конфігурація прив'язок Clique",
      ["Clique general options"] = "Загальні параметри Clique",
      ["Clique: 'default' binding-set"] = "Clique: набір прив'язок 'default'",
      ["Clique: 'enemy' binding-set"] = "Clique: набір прив'язок 'enemy'",
      ["Clique: 'friend' binding-set"] = "Clique: набір прив'язок 'friend'",
      ["Clique: 'global' binding-set"] = "Clique: набір прив'язок 'global'",
      ["Clique: 'hovercast' binding-set"] = "Clique: набір прив'язок 'hovercast'",
      ["Clique: 'ooc' binding-set"] = "Clique: набір прив'язок 'ooc'",
      ["Clique: talent set %d binding-set"] = "Clique: набір прив'язок для таланту %d",
      ["Compact raid frames"] = "Компактні рамки рейду",
      ["Configure binding: '%s'"] = "Конфігурувати прив'язку: '%s'",
      ["Ctrl"] = "Ctrl",
      ["Current: "] = "Поточний: ",
      ["Default"] = "За замовчуванням",
      ["Delete binding"] = "Видалити прив'язку",
      ["Delete profile '%s'"] = "Видалити профіль '%s'",
      ["Delete profile: %s"] = "Видалити профіль: %s",
      ["Disable out of combat clicks when party members enter combat"] = "Вимкнути кліки поза боєм, коли учасники групи потрапляють в бій",
      ["Edit macro"] = "Редагувати макрос",
      ["Enable/Disable binding-sets"] = "Увімкнути/вимкнути набори прив'язок",
      ["Enemy"] = "Ворог",
      ["Frame blacklist"] = "Чорний список рамок",
      ["Frame name"] = "Назва рамки",
      ["Friend"] = "Друг",
      ["General Options"] = "Загальні параметри",
      ["Global bindings (no target)"] = "Загальні прив'язки (без цілі)",
      ["Hovercast bindings (target required)"] = "Прив'язки Hovercast (потрібна ціль)",
      ["In order to specify a binding, move your mouse over the button labelled 'Set binding' and either click with your mouse or press a key on your keyboard. You can modify the binding by holding down a combination of the alt, control and shift keys on your keyboard."] = "Для вказівки прив'язки наведіть курсор миші на кнопку з написом 'Встановити прив'язку' і натисніть мишею або клавішею на клавіатурі. Ви можете змінити прив'язку, утримуючи комбінацію клавіш Alt, Control і Shift на клавіатурі.",
      ["LAlt"] = "ЛAlt",
      ["LCtrl"] = "ЛCtrl",
      ["LMeta"] = "ЛМета",
      ["LShift"] = "ЛShift",
      ["LeftButton"] = "Ліва кнопка",
      ["Meta"] = "Мета",
      ["MiddleButton"] = "Середня кнопка",
      ["MousewheelDown"] = "Прокрутка миші вниз",
      ["MousewheelUp"] = "Прокрутка миші вгору",
      ["No binding set"] = "Немає набору прив'язок",
      ["Open unit menu"] = "Відкрити меню юніта",
      ["Options"] = "Параметри",
      ["Out-of-combat (ONLY)"] = "Поза боєм (ТІЛЬКИ)",
      ["Party member frames"] = "Рамки учасників групи",
      ["Player frame"] = "Рамка гравця",
      ["Player's focus frame"] = "Рамка фокуса гравця",
      ["Player's pet frame"] = "Рамка пета гравця",
      ["Player's target frame"] = "Рамка цілі гравця",
      ["Profile Management:"] = "Управління профілями:",
      ["RAlt"] = "Правий Alt",
      ["RCtrl"] = "Правий Ctrl",
      ["RMeta"] = "Правий Мета",
      ["RShift"] = "Правий Shift",
      ["Remove spell rank"] = "Видалити ранг заклинання",
      ["RightButton"] = "Права кнопка",
      ["Run custom macro"] = "Виконати користувацький макрос",
      ["Run macro"] = "Виконати макрос",
      ["Run macro '%s'"] = "Виконати макрос '%s'",
      ["Save"] = "Зберегти",
      ["Select All"] = "Вибрати все",
      ["Select None"] = "Не вибирати нічого",
      ["Select a binding type"] = "Виберіть тип прив'язки",
      ["Select an options category"] = "Виберіть категорію параметрів",
      ["Select profile: %s"] = "Оберіть профіль: %s",
      ["Set binding"] = "Встановити прив'язку",
      ["Set binding: %s"] = "Встановити прив'язку: %s",
      ["Shift"] = "Shift",
      ["Show unit menu"] = "Показати меню юніта",
      ["Swap profiles based on talent spec"] = "Змінювати профілі в залежності від талантів",
      ["Talent profile: %s"] = "Профіль талантів: %s",
      ["Talents: %s"] = "Таланти: %s",
      ["Target clicked unit"] = "Навести на клікнутий юніт",
      ["Target of focus frame"] = "Ціль рамки фокуса",
      ["Target of target frame"] = "Ціль цілі",
      ["These options control whether or not Clique automatically registers certain Blizzard-created frames for binding. Changes made to these settings will not take effect until the user interface is reloaded."] = "Ці параметри контролюють, чи автоматично Clique реєструє деякі рамки, створені Blizzard, для прив'язки. Зміни, внесені в ці налаштування, наберуть чинності після перезавантаження інтерфейсу користувача.",
      ["This binding is DISABLED"] = "Ця прив'язка ВИМКНЕНА",
      ["This binding is invalid, please delete"] = "Ця прив'язка недійсна, будь ласка, видаліть її",
      ["This panel allows you to blacklist certain frames from being included for Clique bindings. Any frames that are selected in this list will not be registered, although you may have to reload your user interface to have them return to their original bindings."] = "Ця панель дозволяє вам додати деякі рамки до чорного списку, щоб вони не були включені в прив'язки Clique. Будь-які рамки, які ви вибрали в цьому списку, не будуть зареєстровані, хоча, можливо, вам доведеться перезавантажити інтерфейс користувача, щоб вони повернулись до своїх початкових прив'язок.",
      ["Trigger bindings on the 'down' portion of the click (experimental)"] = "Викликати прив'язки при натисканні на 'нижню' частину кліку (експериментально)",
      ["Unknown"] = "Невідомо",
      ["Unknown binding type '%s'"] = "Невідомий тип прив'язки '%s'",
      ["When both the Clique binding configuration window and the spellbook are open, you can set new bindings simply by performing them on the spell icon in your spellbook. Simply move your mouse over a spell and then click or press a key on your keyboard along with any combination of the alt, control, and shift keys. The new binding will be added to your binding configuration."] = "Якщо відкриті як вікно конфігурації прив'язок Clique, так і закладка книги заклинань, ви можете просто встановити нові прив'язки, виконуючи їх на значку заклинання у вашій книзі заклинань. Просто наведіть курсор миші на заклинання, а потім клацніть або натисніть клавішу на клавіатурі разом з будь-якою комбінацією клавіш Alt, Control і Shift. Нова прив'язка буде додана до вашої конфігурації прив'язок.",
      ["You are in Clique binding mode"] = "Ви знаходитесь в режимі прив'язки Clique",
      ["You can use this page to create a custom macro to be run when activating a binding on a unit. When creating this macro you should keep in mind that you will need to specify the target of any actions in the macro by using the 'mouseover' unit, which is the unit you are clicking on. For example, you can do any of the following:\n\n/cast [target=mouseover] Regrowth\n/cast [@mouseover] Regrowth\n/cast [@mouseovertarget] Taunt\n\nHover over the 'Set binding' button below and either click or press a key with any modifiers you would like included. Then edit the box below to contain the macro you would like to have run when this binding is activated."] = "На цій сторінці ви можете створити користувацький макрос, який буде виконуватися при активації прив'язки на юніті. При створенні цього макроса слід пам'ятати, що вам потрібно буде вказати ціль будь-яких дій в макросі, використовуючи одиницю 'mouseover', яка є одиницею, на яку ви клацаєте. Наприклад, ви можете зробити будь-що з наступного:\n\n/cast [target=mouseover] Regrowth\n/cast [@mouseover] Regrowth\n/cast [@mouseovertarget] Taunt\n\nНаведіть курсор миші на кнопку 'Встановити прив'язку' нижче і клацніть або натисніть клавішу з будь-якими модифікаторами, які ви хочете включити. Потім відредагуйте поле нижче, щоб макрос містив те, що ви хочете виконати при активації цієї прив'язки.",
      ["You can use this page to run a custom macro when activating a binding on a unit. Simply type the macro into the box below, and it will be run when this binding is activated."] = "Ви можете використовувати цю сторінку для виконання користувацького макросу при активації прив'язки на юніті. Просто введіть макрос у поле нижче, і він буде виконуватися при активації цієї прив'язки.",
      ["You must enter a macro to be run."] = "Вам потрібно ввести макрос, який буде виконуватися.",
      ["You must reload your user interface to see the changes you made to bindings."] = "Вам потрібно перезавантажити ваш інтерфейс користувача, щоб побачити зміни, які ви внесли в прив'язки.",
    }

    Clique:RegisterLocale(current_locale, baseLocale)
  else
    -- Модуль Clique не завантажений, виконайте відповідні дії або повідомлення
    print("[AddonTranslator]: Модуль Clique не завантажений")
  end
end
